export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _fullNameU = (index: number) =>
  [
    "Valeria Rojas",
    "Mateo Quispe",
    "Camila Huamán",
    "Luis Ángel Paredes",
    "Luciana Chávez",
    "Diego Torres",
    "Alessandra Flores",
    "Josué Mendoza",
    "Ximena Vargas",
    "Andrés Salas",
    "Kiara Navarro",
    "Sebastián Gómez",
    "Mía Ríos",
    "Jorge Alvarado",
    "Danna Ramos",
    "Carlos Peña",
    "Isabela Herrera",
    "Bryan Cárdenas",
    "Romina Ponce",
    "Joaquín León",
    "Fernanda Silva",
    "Cristian Gutiérrez",
    "Nicole Zambrano",
    "Álvaro Ticona",
    "Fiorella Cabrera",
    "Gabriel Soto",
    "Ariana Valverde",
    "Daniel Castro",
    "Allison Luján",
    "Kevin Estrada",
    "Natalia Meza",
  ][index];

export const _userNameU = (index: number) =>
  [
    "valeria.15",
    "mateo_x",
    "camihuaman.z",
    "luangel_123",
    "lucianach_15",
    "diegotorres.x",
    "aless.flores",
    "josue_mdz",
    "xime.vg",
    "andres_s",
    "kiara._n",
    "sebagomez.z",
    "miarios15",
    "j.alvarado",
    "dannaramos_",
    "carlos_pe",
    "isaherrera15",
    "bry_cardenas",
    "romi_ponce",
    "joaquinl.z",
    "fer_silva",
    "cris.gtz",
    "nic.zam",
    "alv.tico",
    "fio_cabrera",
    "gab_soto",
    "ari.valv",
    "dan_castro",
    "allilujan",
    "kevinestrd",
    "nata.meza",
  ][index];

export const _messageU = (index: number) =>
  [
    "oe vieron lo que pasó en clase de historia?",
    "sí jajaj el profe se cayó cuando tropezó con el cable",
    "jajaja parecía abuelito caminando",
    "me dio pena un poco, pero fue chistoso",
    "el Kevin se mataba de risa, como siempre el payaso de la clase",
    "ya pues no exageren, pobre profe",
    "qué payaso ni qué nada, Kevin siempre hace roche",
    "siempre quiere llamar la atención, da pena",
    "habla causa, no te metas con Kevin",
    "uyyy el defensor aparece jaja",
    "a mí me llegó lo que dijo el profe, nos echó la culpa",
    "sí mano, ni siquiera hicimos nada",
    "el Bryan sí fue el que jaló el cable, yo lo vi",
    "no seas mentiroso pe, yo estaba lejos",
    "mentiroso tú, siempre haciendo que otros paguen",
    "ya cálmense, es solo un accidente",
    "la Ximena no dijo ni media palabra, como siempre muda",
    "mejor muda que andar hablando tonteras como tú",
    "respeta pe, no te pases",
    "jajaja pero Xime sí se quedó calladaza",
    "por qué siempre se meten con ella?",
    "porque es rara pues, no habla nada",
    "yo la veo normal, es buena gente",
    "sí, además saca buenas notas, algo que algunos no",
    "uyy esa fue directa para el Bryan jaja",
    "ya ya no se peleen, mejor hablemos del trabajo de inglés",
    "cierto, ya hicieron su parte?",
    "aún no, recién voy a hacer el ppt",
    "yo ya lo mandé, fácilito estaba",
    "a mí me toca exponer, qué nervios",
    "tranqui, tú hablas bien, no como el Joaquín jaja",
  ][index];

export const _dateU = (index: number) =>
  [
    "2025-05-25 09:00",
    "2025-05-25 09:01",
    "2025-05-25 09:02",
    "2025-05-25 09:03",
    "2025-05-25 09:04",
    "2025-05-25 09:05",
    "2025-05-25 09:06",
    "2025-05-25 09:07",
    "2025-05-25 09:08",
    "2025-05-25 09:09",
    "2025-05-25 09:10",
    "2025-05-25 09:11",
    "2025-05-25 09:12",
    "2025-05-25 09:13",
    "2025-05-25 09:14",
    "2025-05-25 09:15",
    "2025-05-25 09:16",
    "2025-05-25 09:17",
    "2025-05-25 09:18",
    "2025-05-25 09:19",
    "2025-05-25 09:20",
    "2025-05-25 09:21",
    "2025-05-25 09:22",
    "2025-05-25 09:23",
    "2025-05-25 09:24",
    "2025-05-25 09:25",
    "2025-05-25 09:26",
    "2025-05-25 09:27",
    "2025-05-25 09:28",
    "2025-05-25 09:29",
    "2025-05-25 09:30",
  ][index];

export const _riskLevelU = (index: number) =>
  [
    "Bajo",
    "Medio",
    "Medio",
    "Bajo",
    "Medio",
    "Bajo",
    "Medio",
    "Medio",
    "Bajo",
    "Bajo",
    "Bajo",
    "Bajo",
    "Bajo",
    "Bajo",
    "Medio",
    "Bajo",
    "Medio",
    "Alto",
    "Bajo",
    "Medio",
    "Bajo",
    "Medio",
    "Bajo",
    "Bajo",
    "Bajo",
    "Bajo",
    "Bajo",
    "Bajo",
    "Medio",
    "Bajo",
    "Alto",
  ][index];

